import json
import logging
from typing import Any
from jinja2 import Environment, PackageLoader, select_autoescape, FileSystemLoader
import os

from workflow_engine.chat.models import RequirementSpec, ChatMessage, ProcessingStep
from workflow_engine.cache.cached_llm import CachedLLMProvider

logger = logging.getLogger(__name__)

class LLMOutputParseError(Exception):
    pass

class RequirementExtractor:
    def __init__(self, llm_provider: CachedLLMProvider):
        self.llm_provider = llm_provider
        self.env = Environment(
            loader=FileSystemLoader(os.path.join(os.path.dirname(__file__), "prompts")),
            autoescape=select_autoescape()
        )
    
    async def extract(self, messages: list[ChatMessage]) -> RequirementSpec:
        """
        Sends full conversation history to LLM with EXTRACTION system prompt.
        Returns structured RequirementSpec.
        """
        template = self.env.get_template("extraction.jinja2")
        
        # Serialize history for prompt
        history_text = ""
        for msg in messages:
            history_text += f"{msg.role.upper()}: {msg.content}\n"
            
        prompt = template.render(messages=history_text)
        
        # We can use caching based on the conversation history
        # We will use the cache key inherently generated by CachedLLMProvider based on the prompt text
        try:
            raw_response = await self.llm_provider.complete(prompt, temperature=0.0)
            
            # Clean possible markdown wrap
            cleaned = raw_response.strip()
            if cleaned.startswith("```json"):
                cleaned = cleaned[7:]
            if cleaned.startswith("```"):
                cleaned = cleaned[3:]
            if cleaned.endswith("```"):
                cleaned = cleaned[:-3]
            cleaned = cleaned.strip()
            
            data = json.loads(cleaned)
            
            # Reconstruct ProcessingSteps
            steps_data = data.get("processing_steps", [])
            processing_steps = [ProcessingStep(**step) for step in steps_data] if isinstance(steps_data, list) else []
            data["processing_steps"] = processing_steps
            
            return RequirementSpec(**data)
            
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse LLM RequirementSpec output: {e}\nRaw Output: {raw_response}")
            raise LLMOutputParseError("LLM response was not valid JSON for RequirementSpec") from e
        except Exception as e:
            import traceback
            traceback.print_exc()
            raise LLMOutputParseError(str(e)) from e
